name: flutter_form_bloc_plus
description: Create Beautiful Forms in Flutter. The easiest way to Prefill, Async Validation, Update Form Fields, and Show Progress, Failures or Navigate by Reacting to the Form State.
version: 0.32.0
homepage: https://github.com/danialb007/form_bloc_plus/tree/master/packages/flutter_form_bloc_plus
repository: https://github.com/danialb007/form_bloc_plus/tree/master/packages/flutter_form_bloc_plus
issue_tracker: https://github.com/danialb007/form_bloc_plus/issues

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  # form_bloc_plus: ^0.32.0
  form_bloc_plus:
    path: ../form_bloc_plus
  equatable: ^2.0.7
  rxdart: ^0.28.0
  flutter_keyboard_visibility: ^6.0.0
  collection: ^1.19.1
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
